name: Legacy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install Dependencies
      run: npm install
      
    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Build Project
      run: npm run build
      # Intentional bug: continue-on-error makes the workflow pass even if the build fails
      continue-on-error: true
    
    - name: Run Tests
      # Tests will pass due to our test setup
      run: npm test
    
    - name: Run Linting
      # This is a dummy step that always succeeds
      run: npm run lint